name: Run Supabase ETL
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install python-dotenv psycopg2-binary pandas sqlalchemy supabase requests
      - name: Run ETL
        env:
          DB_HOST: "aws-1-us-west-2.pooler.supabase.com"
          DB_PORT: "5432"
          DB_NAME: "postgres"
          DB_USER: "postgres.jaluakardtzemqerpdpk"
          DB_PASSWORD: "Un61zM51qN30O3Nw"
          SUPABASE_URL: "https://jaluakardtzemqerpdpk.supabase.co"
                    
            run:
              python api_etl.py
